#!/usr/bin/env bash
# display information about subdomains.
function dig_into_domain()
{
	dig "$2.$1" | grep -A1 'ANSWER SECTION:'| grep "$1" |awk -v sd="$2" 'NF {print "The subdomain " sd " is a " $4 " record and points to " $5}'
}
if [ $# -eq 1 ]; then
	for value in 'www' 'lb-01' 'web-01' 'web-02';do
		dig_into_domain "$1" "$value"
	done
else
	dig_into_domain "$1" "$2"
fi
