#!/usr/bin/env bash
# This scrip show a file description
if [ -a "holbertonschool" ]
then
	echo "holbertonschool file exists"

	if [ -s "holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "holbertonschool" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exists"
fi
