#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 774 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
